services:
  mysql:
    image: mysql:8.0
    container_name: classroom_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: classroom_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 15

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classroom_api
    restart: on-failure
    command: ["go", "run", "."]
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_DSN: root:password@tcp(mysql:3306)/classroom_db?charset=utf8mb4&parseTime=True&loc=Local

volumes:
  mysql_data:
